export const CINEMATIC_CONFIG = {
  TOTAL_FRAMES: 995,
  FRAME_PATH: '/frames/frame_{id}.jpg',
  CACHE_WINDOW: 80,
  MOBILE_CACHE_WINDOW: 40,
  MAX_DEVICE_PIXEL_RATIO: 2,
  SCROLL_DISTANCE_VH: 800,
};
